// Maps hero name (Russian or English, case-insensitive) → image slug
const heroSlugMap: Record<string, string> = {
  // Russian names (Blizzard RU)
  'ань жань': 'anran',
  'домина': 'domina',
  'мидзуки': 'mizuki',
  'реактивная киса': 'jetpack-cat',
  'эмре': 'emre',
  'вендетта': 'vendetta',
  'd.va': 'dva',
  'д.ва': 'dva',
  'авентюра': 'venture',
  'азарт': 'hazard',
  'ана': 'ana',
  'ангел': 'mercy',
  'бастион': 'bastion',
  'батист': 'baptiste',
  'бригитта': 'brigitte',
  'гэндзи': 'genji',
  'дзенъятта': 'zenyatta',
  'жнец': 'reaper',
  'заря': 'zarya',
  'иллари': 'illari',
  'кирико': 'kiriko',
  'королева стервятников': 'junker-queen',
  'крысавчик': 'junkrat',
  'кулак смерти': 'doomfist',
  'кэссиди': 'cassidy',
  'лусио': 'lucio',
  'мауга': 'mauga',
  'мойра': 'moira',
  'мэй': 'mei',
  'ориса': 'orisa',
  'райнхардт': 'reinhardt',
  'раматтра': 'ramattra',
  'роковая вдова': 'widowmaker',
  'сигма': 'sigma',
  'симметра': 'symmetra',
  'соджорн': 'sojourn',
  'солдат-76': 'soldier-76',
  'сомбра': 'sombra',
  'таран': 'wrecking-ball',
  'ткач жизни': 'lifeweaver',
  'торбьорн': 'torbjorn',
  'трейсер': 'tracer',
  'турбосвин': 'roadhog',
  'у ян': 'wuyang',
  'уинстон': 'winston',
  'фарра': 'pharah',
  'фрейя': 'freja',
  'хандзо': 'hanzo',
  'эхо': 'echo',
  'эш': 'ashe',
  'юнона': 'juno',
  // English names
  'ana': 'ana',
  'ashe': 'ashe',
  'baptiste': 'baptiste',
  'bastion': 'bastion',
  'brigitte': 'brigitte',
  'cassidy': 'cassidy',
  'doomfist': 'doomfist',
  'echo': 'echo',
  'genji': 'genji',
  'hanzo': 'hanzo',
  'hazard': 'hazard',
  'illari': 'illari',
  'juno': 'juno',
  'junker queen': 'junker-queen',
  'junkrat': 'junkrat',
  'kiriko': 'kiriko',
  'lifeweaver': 'lifeweaver',
  'lucio': 'lucio',
  'lúcio': 'lucio',
  'mauga': 'mauga',
  'mei': 'mei',
  'mercy': 'mercy',
  'moira': 'moira',
  'orisa': 'orisa',
  'pharah': 'pharah',
  'ramattra': 'ramattra',
  'reaper': 'reaper',
  'reinhardt': 'reinhardt',
  'roadhog': 'roadhog',
  'sigma': 'sigma',
  'sojourn': 'sojourn',
  'soldier: 76': 'soldier-76',
  'soldier-76': 'soldier-76',
  'soldier76': 'soldier-76',
  'sombra': 'sombra',
  'symmetra': 'symmetra',
  'torbjörn': 'torbjorn',
  'torbjorn': 'torbjorn',
  'tracer': 'tracer',
  'venture': 'venture',
  'widowmaker': 'widowmaker',
  'winston': 'winston',
  'wrecking ball': 'wrecking-ball',
  'wrecking-ball': 'wrecking-ball',
  'wuyang': 'wuyang',
  'zarya': 'zarya',
  'zenyatta': 'zenyatta',
  'anran': 'anran',
  'domina': 'domina',
  'mizuki': 'mizuki',
  'emre': 'emre',
  'vendetta': 'vendetta',
  'freja': 'freja',
  'jetpack cat': 'jetpack-cat',
  'jetpack-cat': 'jetpack-cat',
}

export function heroImageUrl(heroName: string): string | undefined {
  const slug = heroSlugMap[heroName.toLowerCase().trim()]
  if (!slug) return undefined
  return `/heroes/${slug}.png`
}
